// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "winsorize_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// corHuberBi
double corHuberBi(const vec& x, const vec& y, const double& c, const double& prob, const double& tol);
RcppExport SEXP winsorize_corHuberBi(SEXP xSEXP, SEXP ySEXP, SEXP cSEXP, SEXP probSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double& >::type c(cSEXP);
    Rcpp::traits::input_parameter< const double& >::type prob(probSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    __result = Rcpp::wrap(corHuberBi(x, y, c, prob, tol));
    return __result;
END_RCPP
}
// corMatHuber
mat corMatHuber(const mat& x, const double& c, const double& prob, const double& tol);
RcppExport SEXP winsorize_corMatHuber(SEXP xSEXP, SEXP cSEXP, SEXP probSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type c(cSEXP);
    Rcpp::traits::input_parameter< const double& >::type prob(probSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    __result = Rcpp::wrap(corMatHuber(x, c, prob, tol));
    return __result;
END_RCPP
}
