# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

corHuberUni <- function(x, y, c) {
    .Call('winsorize_corHuberUni', PACKAGE = 'winsorize', x, y, c)
}

corHuberAdj <- function(x, y, c) {
    .Call('winsorize_corHuberAdj', PACKAGE = 'winsorize', x, y, c)
}

corHuberBi <- function(x, y, c, prob, tol) {
    .Call('winsorize_corHuberBi', PACKAGE = 'winsorize', x, y, c, prob, tol)
}

corMatHuber <- function(x, c, prob, tol) {
    .Call('winsorize_corMatHuber', PACKAGE = 'winsorize', x, c, prob, tol)
}

